iPlug2: IVectorBase Class Reference
IVectorBase Class Reference
IGraphics::IControls::BaseControls
A base interface to be combined with IControl for vectorial controls "IVControls", in order for them to share a common style If you need more flexibility, you're on your own!
#include <IControl.h>
Public Member Functions
IVectorBase (const IColor *pBGColor=&DEFAULT_BGCOLOR, const IColor *pFGColor=&DEFAULT_FGCOLOR, const IColor *pPRColor=&DEFAULT_PRCOLOR, const IColor *pFRColor=&DEFAULT_FRCOLOR, const IColor *pHLColor=&DEFAULT_HLCOLOR, const IColor *pSHColor=&DEFAULT_SHCOLOR, const IColor *pX1Color=&DEFAULT_X1COLOR, const IColor *pX2Color=&DEFAULT_X2COLOR, const IColor *pX3Color=&DEFAULT_X3COLOR)
IVectorBase (const IVStyle &style, bool labelInWidget=false, bool valueInWidget=false)
void AttachIControl (IControl *pControl, const char *label)
void AddColor (const IColor &color)
void AddColors (const IColor *pBGColor=0, const IColor *pFGColor=0, const IColor *pPRColor=0, const IColor *pFRColor=0, const IColor *pHLColor=0, const IColor *pSHColor=0, const IColor *pX1Color=0, const IColor *pX2Color=0, const IColor *pX3Color=0)
void SetColor (int colorIdx, const IColor &color)
void SetColors (const IColor &BGColor, const IColor &FGColor, const IColor &PRColor, const IColor &FRColor, const IColor &HLColor, const IColor &SHColor, const IColor &X1Color, const IColor &X2Color, const IColor &X3Color)
void SetColors (const IVColorSpec &spec)
const IColor & GetColor (int colorIdx) const
void SetLabelStr (const char *label)
void SetValueStr (const char *value)
void SetRoundness (float roundness)
void SetDrawFrame (bool draw)
void SetDrawShadows (bool draw)
void SetEmboss (bool emboss)
void SetShadowOffset (float offset)
void SetFrameThickness (float thickness)
void SetSplashRadius (float radius)
void SetStyle (const IVStyle &style)
IRECT GetAdjustedHandleBounds (IRECT handleBounds) const
void DrawSplash (IGraphics &g)
virtual void DrawBackGround (IGraphics &g, const IRECT &rect)
virtual void DrawWidget (IGraphics &g)
virtual void DrawLabel (IGraphics &g)
virtual void DrawValue (IGraphics &g, bool mouseOver)
void DrawPressableCircle (IGraphics &g, const IRECT &bounds, float radius, bool pressed, bool mouseOver)
IRECT DrawPressableRectangle (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver)
/todo
IRECT DrawPressableTriangle (IGraphics &g, const IRECT &bounds, float angle, bool pressed, bool mouseOver)
Draw a triangle-shaped vector button.
IRECT CalculateRects (const IRECT &parent, bool hasHandle=false)
Protected Attributes
IControl * mControl = nullptr
WDL_TypedBuf< IColor > mColors
float mWidgetFrac = 1.f
IVStyle mStyle
bool mLabelInWidget = false
bool mValueInWidget = false
float mSplashRadius = 0.f
float mMaxSplashRadius = 50.f
IRECT mWidgetBounds
IRECT mLabelBounds
IRECT mValueBounds
WDL_String mLabelStr
WDL_String mValueStr
Detailed Description
A base interface to be combined with IControl for vectorial controls "IVControls", in order for them to share a common style If you need more flexibility, you're on your own!
Definition at line 554 of file IControl.h.
Member Function Documentation
IRECT IVectorBase::DrawPressableRectangle (IGraphics & g, const IRECT & bounds, bool pressed, bool mouseOver) inline
/todo
Parameters
IGraphics&g /todo
bounds /todo
pressed /todo
mouseOver /todo
Returns
/todo
Definition at line 742 of file IControl.h.
References IGraphics::DrawRoundRect(), IGraphics::FillRect(), IGraphics::FillRoundRect(), IRECT::GetHSliced(), IRECT::GetTranslated(), IRECT::GetVSliced(), IRECT::H(), IGraphics::PathFill(), IGraphics::PathRect(), and IRECT::W().
IRECT IVectorBase::DrawPressableTriangle (IGraphics & g, const IRECT & bounds, float angle, bool pressed, bool mouseOver) inline
Draw a triangle-shaped vector button.
Parameters
g The IGraphics context used for drawing
bounds Where to draw the button
angle Angle of rotation in degrees
pressed Whether to draw the button pressed or unpressed
mouseOver Whether mouse is currently hovering on control
Definition at line 793 of file IControl.h.
References IGraphics::DrawTriangle(), IGraphics::FillRect(), IGraphics::FillTriangle(), IRECT::GetTranslated(), IRECT::H(), IRECT::MW(), IGraphics::PathFill(), IGraphics::PathTriangle(), and IRECT::W().
The documentation for this class was generated from the following file:
IControl.h